version: "3"

vars:
  PROJECT: ft_hello
  BUILD_DIR: build
  INSTALL_DIR: .install
  GENERATOR: Ninja

  # Conan
  CONAN_PROFILE_HOST: default
  CONAN_PROFILE_BUILD: default
  CONAN_BUILD_TYPE: Release
  CONAN_OUTPUT: "{{.BUILD_DIR}}/conan/{{.CONAN_BUILD_TYPE}}"

  # CMake
  CMAKE_BUILD_TYPE: "{{.CONAN_BUILD_TYPE}}"
  CMAKE_PRESET: "conan-{{lower .CONAN_BUILD_TYPE}}"

  # Tools (optional)
  CMAKE: cmake
  CT: ctest
  NINJA: ninja

tasks:
  default:
    desc: Build (Release) + run tests
    cmds:
      - task: build
      - task: test

  # ----------------------------
  # Conan
  # ----------------------------
  conan:install:
    desc: Install deps via Conan (generates toolchain + presets)
    cmds:
      - mkdir -p "{{.CONAN_OUTPUT}}"
      - >
        conan install .
        -of "{{.CONAN_OUTPUT}}"
        --profile:host "{{.CONAN_PROFILE_HOST}}"
        --profile:build "{{.CONAN_PROFILE_BUILD}}"
        -s build_type="{{.CONAN_BUILD_TYPE}}"
        --build=missing

  conan:lock:create:
    desc: Create lockfile (reproducible deps)
    cmds:
      - conan lock create . -s build_type="{{.CONAN_BUILD_TYPE}}"

#  conan:cache:clean:
#    desc: Clean Conan cache (DANGEROUS: wipes local binaries)
#    prompt: This will remove your local Conan cache. Continue?
#    cmds:
#      - conan remove "*" -c

  # ----------------------------
  # Configure / Build
  # ----------------------------
  configure:
    desc: Configure CMake (uses Conan-generated toolchain/presets)
    deps: [conan:install]
    cmds:
      # If you use Conan CMakeToolchain + CMakePresets:
      - >
        {{.CMAKE}}
        --preset "{{.CMAKE_PRESET}}"
        -S .
        -B "{{.BUILD_DIR}}/{{.CONAN_BUILD_TYPE}}"

  build:
    desc: Build
    deps: [configure]
    cmds:
      - >
        {{.CMAKE}}
        --build "{{.BUILD_DIR}}/{{.CONAN_BUILD_TYPE}}"
        --parallel

  rebuild:
    desc: Clean build dir for this config and build again
    cmds:
      - rm -rf "{{.BUILD_DIR}}/{{.CONAN_BUILD_TYPE}}"
      - task: build

  install:
    desc: Install to local dir
    deps: [build]
    cmds:
      - >
        {{.CMAKE}}
        --install "{{.BUILD_DIR}}/{{.CONAN_BUILD_TYPE}}"
        --prefix "{{.INSTALL_DIR}}/{{.CONAN_BUILD_TYPE}}"

  run:
    desc: Run executable
    deps: [build]
    cmds:
      - "{{.BUILD_DIR}}/{{.CONAN_BUILD_TYPE}}/{{.PROJECT}}"

  # ----------------------------
  # Tests
  # ----------------------------
  test:
    desc: Run tests (ctest)
    deps: [build]
    cmds:
      - >
        {{.CT}}
        --test-dir "{{.BUILD_DIR}}/{{.CONAN_BUILD_TYPE}}"
        --output-on-failure

  test:rerun-failed:
    desc: Re-run only failed tests
    deps: [build]
    cmds:
      - >
        {{.CT}}
        --test-dir "{{.BUILD_DIR}}/{{.CONAN_BUILD_TYPE}}"
        --output-on-failure
        --rerun-failed

  # ----------------------------
  # Code Quality (optional)
  # ----------------------------
  format:
    desc: Format code (clang-format)
    cmds:
      - find . -name "*.cpp" -o -name "*.hpp" -o -name "*.h" | xargs clang-format -i

  tidy:
    desc: Run clang-tidy (assumes compile_commands.json exists)
    deps: [build]
    cmds:
      - >
        run-clang-tidy
        -p "{{.BUILD_DIR}}/{{.CONAN_BUILD_TYPE}}"

  # ----------------------------
  # Clean
  # ----------------------------
  clean:
    desc: Remove build outputs
    cmds:
      - rm -rf "{{.BUILD_DIR}}"
      - rm -rf "{{.INSTALL_DIR}}"

  clean:config:
    desc: Remove build outputs for current config only
    cmds:
      - rm -rf "{{.BUILD_DIR}}/{{.CONAN_BUILD_TYPE}}"
      - rm -rf "{{.CONAN_OUTPUT}}"

  # ----------------------------
  # Docker (optional scaffold)
  # ----------------------------
  docker:build:
    desc: Build Docker image (if you have a Dockerfile)
    cmds:
      - docker build -t "{{.PROJECT}}:dev" .

  docker:run:
    desc: Run Docker image interactively
    cmds:
      - docker run --rm -it "{{.PROJECT}}:dev" bash
