version: "3"

# coann home env ->
dotenv: [".env"]
vars:
  PROJECT: ft_hello
  BUILD_DIR: build
  INSTALL_DIR: .install
  GENERATOR: "Unix Makefiles"

  # Conan
  CONAN_PROFILE_HOST: default
  CONAN_PROFILE_BUILD: default
  CONAN_BUILD_TYPE: Release
  CONAN_OUTPUT: "{{.BUILD_DIR}}/conan/{{.CONAN_BUILD_TYPE}}"

  # CMake
  CMAKE_BUILD_TYPE: "{{.CONAN_BUILD_TYPE}}"
  CMAKE_PRESET: "conan-{{lower .CONAN_BUILD_TYPE}}"

  # Tools (optional)
  CMAKE: cmake
  CT: ctest
  NINJA: ninja

tasks:
  default:
    desc: Build (Release) + run tests
    cmds:
      - task: build
      - task: test

  # ----------------------------
  # Conan
  # ----------------------------
  conan:install:
    desc: Install deps via Conan (generates toolchain + presets)
    cmds:
      - mkdir -p "{{.CONAN_OUTPUT}}"
      - >
        conan install .
        -of "{{.CONAN_OUTPUT}}"
        -pr:h=./profiles/default
        -pr:b="{{.CONAN_PROFILE_BUILD}}"
        -s build_type="{{.CONAN_BUILD_TYPE}}"
        --build=missing


  conan:lock:create:
    desc: Create lockfile (reproducible deps)
    cmds:
      - conan lock create . -s build_type="{{.CONAN_BUILD_TYPE}}"


  # ----------------------------
  # Configure / Build
  # ----------------------------
  configure:
    desc: Configure CMake (uses Conan-generated toolchain/presets)
    deps: [conan:install]
    cmds:
      # If you use Conan CMakeToolchain + CMakePresets:
      - >
        {{.CMAKE}}
        --preset "{{.CMAKE_PRESET}}"
        -S .
        -B "{{.BUILD_DIR}}/{{.CONAN_BUILD_TYPE}}"
        -G "{{.GENERATOR}}" 

  build:
    desc: Build
    deps: [configure]
    cmds:
      - >
        {{.CMAKE}}
        --build "{{.BUILD_DIR}}/{{.CONAN_BUILD_TYPE}}"
        --parallel

  rebuild:
    desc: Clean build dir for this config and build again
    cmds:
      - rm -rf "{{.BUILD_DIR}}/{{.CONAN_BUILD_TYPE}}"
      - task: build

  install:
    desc: Install to local dir
    deps: [build]
    cmds:
      - >
        {{.CMAKE}}
        --install "{{.BUILD_DIR}}/{{.CONAN_BUILD_TYPE}}"
        --prefix "{{.INSTALL_DIR}}/{{.CONAN_BUILD_TYPE}}"

  run:
    desc: Run executable
    deps: [build]
    cmds:
      - "{{.BUILD_DIR}}/{{.CONAN_BUILD_TYPE}}/{{.PROJECT}}"


  # ----------------------------
  # Code Quality (optional)
  # ----------------------------
  format:
    desc: Format code (clang-format)
    cmds:
      - find . -name "*.cpp" -o -name "*.hpp" -o -name "*.h" | xargs clang-format -i

  tidy:
    desc: Run clang-tidy (assumes compile_commands.json exists)
    deps: [build]
    cmds:
      - >
        run-clang-tidy
        -p "{{.BUILD_DIR}}/{{.CONAN_BUILD_TYPE}}"

  # ----------------------------
  # Clean
  # ----------------------------
  clean:
    desc: Remove build outputs
    cmds:
      - rm -rf "{{.BUILD_DIR}}"
      - rm -rf "{{.INSTALL_DIR}}"

  clean:config:
    desc: Remove build outputs for current config only
    cmds:
      - rm -rf "{{.BUILD_DIR}}/{{.CONAN_BUILD_TYPE}}"
      - rm -rf "{{.CONAN_OUTPUT}}"

